### ISSUE TITLE
Should this include tracing middleware?

### ISSUE THREAD

**Issue by jcchavezs** [ngrok/sqlmw#2]
Although the example is good enough for tracing I think providing a middleware for tracing or metrics of popular libraries is worth. I could come up with a PR for this.

**Comment by inconshreveable** [comment]
possibly, although then the package would have dependencies whereas right now it depends only on the standard library which I think is an attractive property for an interface like this.

if we separate it off into a separate go module, i think it would be great to add collection of middleware built on top of this abstraction that would serve as both example and reusable software

**Comment by timbunce** [comment]
> it depends only on the standard library which I think is an attractive property for an interface like this.

I agree. That route often gets painful over time and most of the pain falls on the maintainer not the contributors.

I'd encourage others to develop middleware and link to those other projects from here. (Plus, of course, sites like godoc will show [packages using sqlmw here](https://godoc.org/github.com/ngrok/sqlmw?importers).)

**Comment by inconshreveable** [comment]
closing this for now. we can re-open if there are PRs or we want to have a separate discussion about separate modules in the same repository
