### ISSUE TITLE
middlware for other methods?

### ISSUE THREAD

**Issue by frioux** [ngrok/sqlmw#4]
I am excited that this project exists and it gives me the hooks I need; thanks!  One thing we'd like to do at Zip is forbid the use of non-Context methods, so that we always are able to hook the methods being used.  Would you be interested in another interface, maybe CompleteInterceptor, that allows users to hook more than just the Context functions?

**Comment by inconshreveable** [comment]
interesting. could you accomplish the same goal by injecting a value into the context and then in each interceptor method ensuring that the value in the context exists? or just checking whether the context has a deadline set? i imagine that would allow you to catch those invocations?

**Comment by frioux** [comment]
Oh that works perfectly!  Thanks for the quick response.  In order to help future users I am going to take a stab at adding some doc to all the methods and clarifying what they hook; would that be useful to you?

**Comment by inconshreveable** [comment]
that would be amazing, thank you!

**Comment by frioux** [comment]
great; will do
