### ISSUE TITLE
Is there any methods to modify the result? when query ?

### ISSUE THREAD

**Issue by cjphaha** [ngrok/sqlmw#7]
hi, i want to know how to modify the result when i query the table.
such as
```sql
SELECT * FROM `account`
```

i tried to modify the dest, but failed, the code as follows
```go
func (in *SqlInterceptor) RowsNext(ctx context.Context, rows driver.Rows, dest []driver.Value) error {
	// Edit the dest
	return rows.Next(dest)
}

```
can you help me? thx!

**Comment by inconshreveable** [comment]
apologies but i don't know how to help with this request, perhaps another user is able to provide some guidance though
